### ISSUE TITLE
Subsync error "select reference language"

### ISSUE THREAD

**Issue by Froghut** [hotio/docker-bazarr#2]
Sometimes I get the mentioned error, it seems subsync sometimes doen't know the language of the video file. Might it make sense to use the following additional command line parameters?
`--ref-lang {{episode_language_code3}} --sub-lang {{subtitles_language_code3}}`
see here:
https://github.com/sc0ty/subsync/wiki/Command-line-options
https://github.com/morpheus65535/bazarr/wiki/Settings-General

**Comment by hotio** [comment]
Those were removed, because they produced other errors. It's just an example and it says to adjust for your own personal needs.
