### ISSUE TITLE
No subsync happening

### ISSUE THREAD

**Issue by GitJamz** [hotio/docker-bazarr#3]
Hi,
I switched to this image from linuxserver because of subsync.
I fired up the container from scratch (did not copy earlier configurations). 
Then in settings/general I added the default line under postprocessing:
subsync --cli sync --sub "{{subtitles}}" --ref "{{episode}}" --out "{{subtitles}}" --overwrite

Im not sure if this needs more adjustment? I tried a movie I know has a default embedded subtitle that is correct and then made it download another subtitle that I know is not in sync.
But it didnt fix anything. I check the logs and it says:
BAZARR Post-processing result for file movie/movie.mkv : Nothing returned from command execution

Is it the postprocessing command that is not sufficient at default?

**Comment by hotio** [comment]
What tag did you pull?

**Comment by GitJamz** [comment]
> What tag did you pull?

Humm..
I just did a docker-compose and for image I wrote: 
image: hotio/bazarr

**Comment by hotio** [comment]
then there's no subsync included

**Comment by GitJamz** [comment]
> then there's no subsync included

Ohh I see now,, Im not to used to modifying anything in docker.. I generally always grab the original name to get the "latest" standard tags..
So on image I write:
image: hotio/bazarr:stable-subsync

correct ?

**Comment by hotio** [comment]
yes correct

**Comment by GitJamz** [comment]
> yes correct

Thank You!
In general do I need to change the default subsync command for syncing videos and TV shows subtitles? I looked through their site but looked damn complicated to understand how,w hat and why to modify anything..

**Comment by hotio** [comment]
no idea, I don't do subsync support....
